use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Activity {
    pub slug: &'static str,
    pub name: &'static str,
    pub association: &'static str,
    pub description: &'static str,
    pub horaire: &'static str,
    pub lieu: &'static str,
    pub capacity: u32,
    pub icon: &'static str,
}

pub const ACTIVITIES: &[Activity] = &[
    Activity {
        slug: "basket-fauteuil",
        name: "Basket fauteuil",
        association: "Handi'Sport Lyon",
        description: "Initiez-vous au basket en fauteuil roulant. Encadré par des athlètes paralympiques, cet atelier vous plonge dans l'intensité du handisport.",
        horaire: "09h30 – 10h30",
        lieu: "Gymnase A — Hall principal",
        capacity: 20,
        icon: "🏀",
    },
    Activity {
        slug: "escalade-adaptive",
        name: "Escalade adaptive",
        association: "Grimpe Pour Tous",
        description: "Découvrez l'escalade adaptée à tous les niveaux et capacités. Murs équipés de prises sensorielles et harnais adaptés.",
        horaire: "10h00 – 11h30",
        lieu: "Mur d'escalade — Espace extérieur",
        capacity: 15,
        icon: "🧗",
    },
    Activity {
        slug: "danse-inclusive",
        name: "Danse inclusive",
        association: "Danse & Diversité",
        description: "Un atelier de danse contemporaine qui abolit les frontières. Chorégraphie collective mêlant danseurs valides et en situation de handicap.",
        horaire: "11h00 – 12h00",
        lieu: "Salle de danse — Bâtiment B",
        capacity: 25,
        icon: "💃",
    },
    Activity {
        slug: "secourisme-express",
        name: "Secourisme express",
        association: "Croix-Rouge française",
        description: "Apprenez les gestes qui sauvent en 45 minutes. Massage cardiaque, position latérale de sécurité et utilisation du défibrillateur.",
        horaire: "12h30 – 13h15",
        lieu: "Salle polyvalente — RDC",
        capacity: 30,
        icon: "🩺",
    },
    Activity {
        slug: "atelier-handicap",
        name: "Sensibilisation au handicap",
        association: "APF France handicap",
        description: "Parcours immersif en fauteuil, lunettes de simulation basse vision, jeux en langue des signes. Changez de regard sur le handicap.",
        horaire: "14h00 – 15h00",
        lieu: "Parvis — Stands extérieurs",
        capacity: 40,
        icon: "👁️",
    },
    Activity {
        slug: "tir-arc-adapte",
        name: "Tir à l'arc adapté",
        association: "Arc-en-Ciel Sport",
        description: "Le tir à l'arc est l'un des sports les plus inclusifs. Matériel adapté fourni, encadrement par des moniteurs diplômés.",
        horaire: "15h00 – 16h00",
        lieu: "Terrain de tir — Pelouse sud",
        capacity: 12,
        icon: "🏹",
    },
    Activity {
        slug: "yoga-accessible",
        name: "Yoga accessible",
        association: "Souffle & Mouvement",
        description: "Séance de yoga sur chaise et au sol, adaptée à toutes les mobilités. Relaxation, respiration et étirements doux.",
        horaire: "16h00 – 17h00",
        lieu: "Jardin — Espace zen",
        capacity: 20,
        icon: "🧘",
    },
    Activity {
        slug: "quiz-sport-inclusif",
        name: "Quiz sport & inclusion",
        association: "Up Sport!",
        description: "Testez vos connaissances sur le sport inclusif, les Jeux Paralympiques et l'histoire du handisport en France. Lots à gagner !",
        horaire: "17h30 – 18h30",
        lieu: "Scène principale — Amphithéâtre",
        capacity: 100,
        icon: "🧠",
    },
];
